-- The CMO is interested in understanding how the sales of different 
-- product families are affected by promotional campaigns. 
-- To do so, for each product family, show the total number of units sold, 
-- as well as the percentage of units sold that had a valid promotion 
-- among total units sold. If there are NULLS in the result, 
-- replace them with zeroes. Promotion is valid if it's not empty 
-- and it's contained inside promotions table.

