-- You are given a day worth of scheduled departure and arrival times 
-- of trains at one train station. One platform can only accommodate 
-- one train from the beginning of the minute it's scheduled to arrive 
-- until the end of the minute it's scheduled to depart. 
-- Find the minimum number of platforms necessary to accommodate the 
-- entire scheduled traffic.